# Generated by Django 2.1.4 on 2018-12-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passport_url',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
