# Generated by Django 2.1.4 on 2018-12-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181228_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passport',
            new_name='passport_url',
        ),
    ]
