# Generated by Django 2.1.4 on 2019-01-02 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='departing_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='booking',
            name='returning_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
