# Generated by Django 2.1.4 on 2019-01-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20190102_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='returning_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
