# Generated by Django 2.1.4 on 2019-01-02 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20190102_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='type',
            new_name='flight_type',
        ),
    ]
